using System.Collections.Generic;

namespace CoffeeNChill.Functions.DTOs
{

    // ============================================================
    // POE PART 2:
    // Client request DTO for POST /api/orders/queue.
    //
    // Only client-supplied order information is accepted here.
    // OrderTimestamp is deliberately NOT supplied by the client;
    // it is generated by the server in OrderFunctions.
    // ============================================================
    public class CreateOrderRequest
    {
        public string? OrderId { get; set; }

        public string? CustomerName { get; set; }

        public List<string>? SelectedItemSKUs { get; set; }

        public decimal TotalPrice { get; set; }
    }
}